### PR TITLE
Initial English Translation Contribution

### PR DESCRIPTION
**Pull request by alancnet**
There are a few things I'm not sure of:

`config.autoGetTableCount` seems to be incorrect in zh-cn also. Maybe it should be "查询表时自动获取总行数" instead of "查询表时自动获取表总数"?

`config.queryWithSchema`: this feature doesn't seem to change anything when I toggle it on or off. Schema for tables is always loaded.

`config.autoPagingSQL`: This feature seems to only apply a default `LIMIT` where `config.autoGetTableCount` enabled pagination. If that is the case in all databases, then I'd suggest

```JSON
"config.autoPagingSQL": "Apply default limit to SELECT statements.",
"config.autoGetTableCount": "Enable pagination of query results.",
```

### CODE REVIEW

**Comment by alancnet** [comment]
Also what is Code Len?

**Comment by cweijan** [comment]
Thank you for pointing these issues out.
1. "autoGetTableCount" should indeed be "行数" rather than "表总数"
2. "queryWithSchema" currently only takes effect for PostgreSQL and SQL Server. I forgot why this option was added. It should be deprecated.
3. "autoPagingSQL" refers to automatically adding pagination (ctrl+enter) to the executed SQL.

Code Len refers to the button suspended in the editor, which was proposed by VS Code.
image

**Comment by cweijan** [comment]
Have you registered a Database Client account? If so, please email me your registered email address and I would like to give you one year of premium.

**Comment by cweijan** [comment]
I didn't notice the "Initial" in your title, I seemed to have merged too quickly🥲.

**Comment by alancnet** [comment]
Thanks @cweijan I appreciate it! I'm `github@alanc.net`, and already subscribed on Premium. No need to compensate me. I just like to help :)

Regarding "initial", I feel the contributions are good, just incomplete as I don't understand all the features, but you're good to merge 👍

Cheers!

**Comment by cweijan** [comment]
Thanks, I've added 1 year premium to your account.

**Comment by alancnet** [comment]
Oh [Code Lens](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup) not [Len](https://www.w3schools.com/sql/func_sqlserver_len.asp) 😇

**Pull request merged**
